Repository Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend, pull requests merged in 2024-05, with the labels that each got.

#120 Totally documented DTO's and controllers
  src/main/java/com/springboot/connectmate/controllers/AmazonConnectController.java
  src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectAgentDTO.java
  src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectInstanceDTO.java
  src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectQueueDTO.java
  src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectRoutingProfileDTO.java
  src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectUserDTO.java
  src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectUserDataDTO.java
  src/main/java/com/springboot/connectmate/services/AmazonConnectService.java
  src/main/java/com/springboot/connectmate/services/impl/AmazonConnectServiceImpl.java
  src/test/java/com/springboot/connectmate/SpringbootConnectmateRestApiApplicationTests.java
Labels: documentation

#121 1000th BD refactor and first new endpoint yayyy
  .github/workflows/main.yml
  src/main/java/com/springboot/connectmate/controllers/AlertController.java
  src/main/java/com/springboot/connectmate/controllers/MetricsInfoController.java
  src/main/java/com/springboot/connectmate/controllers/ThresholdBreachesController.java
  src/main/java/com/springboot/connectmate/dtos/Alert/ThresholdBreachDTO.java
  src/main/java/com/springboot/connectmate/models/MetricsInfo.java
  src/main/java/com/springboot/connectmate/models/ThresholdBreaches.java
  src/main/java/com/springboot/connectmate/models/Users.java
  src/main/java/com/springboot/connectmate/repositories/MetricsInfoRepository.java
  src/main/java/com/springboot/connectmate/repositories/UsersRepository.java
  src/main/java/com/springboot/connectmate/services/MetricsInfoService.java
  src/main/java/com/springboot/connectmate/services/ThresholdBreachesService.java
  src/main/java/com/springboot/connectmate/services/UsersService.java
  src/main/java/com/springboot/connectmate/services/impl/MetricsInfoServiceImpl.java
  src/main/java/com/springboot/connectmate/services/impl/ThresholdBreachesServiceImpl.java
  src/main/java/com/springboot/connectmate/services/impl/UsersServiceImpl.java
  src/test/java/com/springboot/connectmate/SpringbootConnectmateRestApiApplicationTests.java
Labels: enhancement, Pruebas

#143 Metrics by agent and by queue
  src/main/java/com/springboot/connectmate/controllers/AmazonConnectInterpreterController.java
  src/main/java/com/springboot/connectmate/controllers/ConnectMetricController.java
  src/main/java/com/springboot/connectmate/controllers/ConnectQueueController.java
  src/main/java/com/springboot/connectmate/services/AmazonConnectInterpreterService.java
  src/main/java/com/springboot/connectmate/services/AmazonConnectService.java
  src/main/java/com/springboot/connectmate/services/impl/AmazonConnectInterpreterServiceImpl.java
  src/main/java/com/springboot/connectmate/services/impl/AmazonConnectServiceImpl.java
Labels: enhancement

#152 Standard for Testing and DTO for metrics created
  src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectCurrentMetricDTO.java
  src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectMetricDTO.java
  src/test/java/com/springboot/connectmate/SpringbootConnectmateRestApiApplicationTests.java
Labels: enhancement, Pruebas

#151 Email service ready, template finished. SMS not ready, not implemented. (unknown, no merge yet)
  pom.xml
  src/main/java/com/springboot/connectmate/controllers/EmailController.java
  src/main/java/com/springboot/connectmate/services/EmailService.java
  src/main/java/com/springboot/connectmate/services/impl/EmailServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#157 Insight creation
  src/main/java/com/springboot/connectmate/config/TestConfig.java
  src/main/java/com/springboot/connectmate/controllers/BedrockController.java
  src/main/java/com/springboot/connectmate/controllers/TestController.java
  src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
  src/main/java/com/springboot/connectmate/dtos/ThresholdBreachInsight/InsightDTO.java
  src/main/java/com/springboot/connectmate/dtos/ThresholdBreachInsight/KpiDataDTO.java
  src/main/java/com/springboot/connectmate/enums/ResponseField.java
  src/main/java/com/springboot/connectmate/services/BedrockService.java
  src/main/java/com/springboot/connectmate/services/TestService.java
  src/main/java/com/springboot/connectmate/services/ThresholdBreachInsightService.java
  src/main/java/com/springboot/connectmate/services/impl/BedrockServiceImpl.java
  src/main/java/com/springboot/connectmate/services/impl/TestServiceImpl.java
  src/main/java/com/springboot/connectmate/services/impl/ThresholdBreachInsightServiceImpl.java
Labels: enhancement
